== Preface

It was not till within a few years before the author`'s decease,
that he entertained a design to leave behind him a memorial of this nature.
But being requested about the year 1742, to turn his thoughts this way,
by one of his sons who had been much less under his
immediate tuition than the rest of his children,
and consequently less acquainted with many particulars of his life, he replied,
that though he had been mostly easy in relation to writing any thing by way of
journal of his labors--yet it had not passed wholly without thoughts concerning it;
and so frequently of late, as to have somewhat turned his inclinations that way.
From this time it fixed more closely upon him,
and he employed great part of his leisure time, when health permitted,
in drawing up the first part of the ensuing memoirs,
which extends only to the time of his return from his first visit to America,
and was finished but a few weeks before his decease, under great weakness of body.
The plain, sensible and lively manner, in which this account is drawn up,
occasions regret that he had not earlier engaged herein,
and that the many interesting and instructive observations,
that must have occurred during the remaining part of his life, are now lost.

The succeeding part of this collection,
has been compiled from the short notes he kept of his several visits,
and some other papers and letters.

It was not without hesitation,
that some parts of the following collection were committed to the press;
such as the summary journals of several of his visits.
Nevertheless,
as even these short hints may possibly occasion
in the minds of many who remember those visits,
and his labors therein, some useful considerations,
it was thought most proper to retain them.

A painful, deep, searching, laborious ministry was oftentimes the author`'s portion;
accompanied with a zealous concern, that all might come to the certain knowledge,
and inward experience of a holy living principle operating in the hearts of mankind;
in order to lead them from error and unrighteousness, into all truth,
and into the practice of every Christian virtue.
And to those who read with a view to profit, not barely amusement;
and in order that they may both be informed of, and animated by example,
to come up in their respective duties, the perusal, we hope, will be beneficial.

This was the general tendency of his labors in the ministry,
as many now living can testify;
and in the following sheets the same important
doctrine is strongly and frequently inculcated,
and is now earnestly recommended to the reader, with desires,
that the many truths herein delivered, may have a due effect upon every mind;
and that those especially who have been witnesses of his zeal and fervency, may,
in calling his services among them to their remembrance,
be incited to follow him as he followed Christ,
and thus secure to themselves the benefits he diligently labored for;
and at the same time to pay the most expressive regard to his memory.
